# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# development:
#   secret_key_base: 741be3b326f5fe6c6a46a72103ed9b3a8ae537113b2e6159231c89cd72b44a29ff42ffd5ae7c77555b72a94f6245dedf85f9f115e96707371a357be2629908e0

# test:
#   secret_key_base: 8c138b84ce6caeb6bb878520f86abab175bae8b4c0b223929320528eeacdc3f91583b4c4f31d6ed8793c93e9f828fab4f94ef45735d30acb03b0e3137d256209

# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# production:
#   secret_key_base: <%#= ENV["SECRET_KEY_BASE"] %>

development:
  admin_name: First User
  admin_email: simon@vemm.com.br
  admin_password: changeme
  domain_name: vemm.com.br
  secret_key_base: 5a896cefd9034cfd21883a9aa82226f64a71d87530e8ad7a736f35da6d18b397a0eba53bd499987ccf1b9799d66ab53bd8272ce719e31b6a2bddd09f2a6533fa
  email_provider_username: <%= ENV["EMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PASSWORD"] %>
  email_provider_smtp: <%= ENV["EMAIL_SMTP"] %>

test:
  domain_name: example.com 
  secret_key_base: 33a925ba9dc7e9309fc91f52ee3f0da2f328be632847b2835e6a5d3a2f0c716623e73025ae8e2df8a52884b268e76f6a2b02e9206d145229d8a00a65a5c533d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["EMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PASSWORD"] %>
  email_provider_smtp: <%= ENV["EMAIL_SMTP"] %>

staging:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["EMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PASSWORD"] %>
  email_provider_smtp: <%= ENV["EMAIL_SMTP"] %>

